remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-remote-theme

title: Test Site
navbar-links:
  About Me: "aboutme"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"
